sudo: required
services:
  - docker
install:
  - docker build -t askomics-ie .
  - docker run -d -p 6543:6543 askomics-ie
before_script:
   - sleep 1m
script:
  - "curl -v -H \"X-Requested-With: XMLHttpRequest\" -X GET http://localhost:6543/startpoints"