sudo: required
services:
  - docker
install:
  - docker build -t askomics-ie .
  - docker run -d -p 6543:6543 -p 8890:8890 -e ASKO_files_dir='/tmp/askomics-ie' -e ASKO_database_path='/tmp/askomics-ie/database.db' -e ASKO_load_url='http://localhost:6543' -e SPARQL_UPDATE='true' -e GALAXY_USER_NAME='jdoe' -e GALAXY_USER_EMAIL='jdoe@example.com' -e ASKOMICS_API_KEY='jdoe' askomics_ie:19.01.3
before_script:
   - sleep 1m
script:
  - "curl -v -H \"X-Requested-With: XMLHttpRequest\" -X GET http://localhost:6543/startpoints"